// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NewDownloadController from "./NewDownloadController";
application.register("newDownload", NewDownloadController)

import SearchController from "./SearchController";
application.register("search", SearchController)

import SearchesController from "./SearchesController";
application.register("searches", SearchesController)


import AlertsController from "./alerts_controller";
application.register("alerts", AlertsController)
